{% set name = "gwinc" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91cdf8c08cef6c67fa0462c7c522ed1f4ff4e727c969e7f6467b088951ebb6c0

build:
  entry_points:
    - gwinc = gwinc.__main__:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=30.3.0
    - setuptools_scm
  run:
    - h5py
    - ipython
    - matplotlib-base
    - numpy
    - python >=3.6
    - pyyaml
    - scipy

test:
  imports:
    - gwinc
    - gwinc.ifo
  commands:
    - gwinc --help
    - python -c "import gwinc; print(' '.join(gwinc.IFOS))"
    - python -m gwinc.ifo -s test.png

about:
  home: https://git.ligo.org/gwinc/pygwinc
  dev_url: https://git.ligo.org/gwinc/pygwinc.git
  doc_url: https://gwinc.docs.ligo.org/pygwinc/
  summary: Gravitational Wave Interferometer Noise Calculator
  license: Unlicense
  license_file: LICENSE
  description: |
    `gwinc` is a multi-faceted tool for processing and plotting
    noise budgets for ground-based gravitational wave detectors.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
